// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taxmaster.Infrastructure;

#nullable disable

namespace Taxmaster.Infrastructure.Migrations
{
    [DbContext(typeof(RuleContext))]
    partial class RuleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taxmaster.Infrastructure.DbDateRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UtcEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UtcStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("DbDateRule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2029, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2029, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2032, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2033, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2032, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2034, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2033, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2034, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2036, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2037, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2036, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2038, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2037, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2039, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2038, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.2m,
                            UtcEndTime = new DateTime(2040, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2039, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2027, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2028, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2028, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2029, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2029, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2030, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2030, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2031, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2031, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2032, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2032, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2033, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2033, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2034, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2034, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2035, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2035, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2036, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2036, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2037, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2037, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2038, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2038, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.4m,
                            UtcEndTime = new DateTime(2039, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2039, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2027, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2028, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2029, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2029, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2030, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2031, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2032, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2032, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2033, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2033, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2034, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2034, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2035, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2035, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2036, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2036, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2037, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2037, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2038, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2038, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2039, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2039, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 61,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2020, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 62,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2021, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 63,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 64,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2023, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 65,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 66,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 67,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 68,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2027, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2027, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 69,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2028, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2028, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 70,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2029, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2029, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 71,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2030, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2030, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 72,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2031, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2031, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 73,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2032, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2032, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 74,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2033, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2033, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 75,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2034, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2034, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 76,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2035, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2035, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 77,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2036, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2036, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 78,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2037, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2037, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 79,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2038, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2038, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 80,
                            MunicipalityId = "copenhagen",
                            TaxRate = 0.1m,
                            UtcEndTime = new DateTime(2039, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            UtcStartTime = new DateTime(2039, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Taxmaster.Infrastructure.DbMunicipality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = "copenhagen"
                        },
                        new
                        {
                            Id = "aarhus"
                        });
                });

            modelBuilder.Entity("Taxmaster.Infrastructure.DbDateRule", b =>
                {
                    b.HasOne("Taxmaster.Infrastructure.DbMunicipality", "Municipality")
                        .WithMany("Rules")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Taxmaster.Infrastructure.DbMunicipality", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
